config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers
  end
  resources :users

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]


	def create
		@answer.user = current_user
		@question = Question.find(params[:question_id])
		@answer = @question.answers.create(answer_params)
		@answer.save
		redirect_to question_path(@question)
	end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])
		@answer.destroy
		redirect_to question_path(@question)
	end


	private
		def answer_params
			params.require(:answer).permit(:body, :rating, :email => current_user.email)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]



  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question.views_count += 1
    @question.save
  end

  def soloved
    @question.update_attributes(soloved: true)
    redirect_to questions_path(soloved: false)
  end

  # GET /questions/new
  def new
    @question = Question.new
    @user = current_user
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @user = current_user
    @question = @user.questions.create(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', root_path %>
<%= link_to 'Users', users_path %>
<% if user_signed_in? %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<h4>hello, <%= current_user.email %>
<% else %>
<%= link_to 'Login', new_user_session_path %>
<%= link_to 'Registration', new_user_registration_path %>
<% end %>
<hr>



<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table class="table">
  <thead>
    <tr>
      <th>From</th>
      <th>Title</th>
      <th>Body</th>
      <th>Views count</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.user.email %></td>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
        <td><%= question.views_count %></td>
        <td><%= question.rating %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% if @question.soloved? %>
<h2>Soloved!</h2>
<% else %>
<h2>Unsoloved</h2>
<% end %>
<% if current_user %>
<%= link_to 'This question soloved!' %>
<% end %> 
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<p>
  <strong>Views count:</strong>
  <%= @question.views_count %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @question.rating %>
</p>
<p>
  <strong>Creation time:</strong>
  <%= @question.created_at %>
</p>
<p>
    <strong>From:</strong>
    <%= link_to user_path(@question.user.id) do %>
    <%= @question.user.email %>
    <% end %>
  </p>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>
<br/>
<% if !@question.answers.empty? %>
<h2>This question have <%= pluralize(@question.answers.count, "answer") %></h2>
<% @question.answers.each do |answer| %>
  <p>
    <strong>From:</strong>
    <%= answer.from %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= answer.body %>
  </p>
  <p>
    <strong>Rating:</strong>
    <%= answer.rating %>
  </p>
  <p>
  <strong>Creation time:</strong>
  <%= answer.created_at %>
</p>
  <%= link_to 'Delete answer', [answer.question, answer], method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>
<% else %>
<h2>No any answers yet. Be first!<h2>
<% end %>

<h2>Add a answer:</h2>
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= user.email %>
	<%= link_to 'Show', user_path(user) %>
<% end %>

app/views/users/show.html.erb
<h2>You are on <%= @user.email %> page</h2>
<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Title</th>
      <th>Body</th>
      <th>Views count</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.questions.each do |question| %>
      <tr>
        <td><%= question.user.email %>|</td>
        <td><%= question.title %>|</td>
        <td><%= question.body %>|</td>
        <td><%= question.views_count %>|</td>
        <td><%= question.rating %>|</td>
        <td><%= link_to 'Show', question %>|</td>
        <td><%= link_to 'Edit', edit_question_path(question) %>|</td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>|</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>